### ISSUE TITLE
在 ubuntu20 下，无法完成登录操作

### ISSUE THREAD

**Issue by little-snow-fox** [cissusnar/kuaitie#111]
**BUG描述**
在 ubuntu20 下执行登录命令的时候一直出现登录失败，我在 mac 端上试过帐号密码是对的，版本应该是最新的，因为刚刚按照官方说明文档完成安装

**如何复现**
1. clipctl -U login

**截屏**
```
samoyed@9196238eee3a:~/.config$ clipctl -U login
account: 作者已看到,隐藏用户名
passcode: 
login failed

```

**桌面版:**
```
snowfox@snowfox-work:~$ cat /etc/issue
KDE neon 5.22 \n \l

snowfox@snowfox-work:~$ cat /proc/version
Linux version 5.4.0-74-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021

snowfox@snowfox-work:~$ docker -v
Docker version 20.10.7, build f0df350

snowfox@snowfox-work:~$ lsb_release -is
Neon
snowfox@snowfox-work:~$ lsb_release -rs
20.04

root@snowfox-work:/opt/sysbox# cat /etc/os-release 
NAME="KDE neon"
VERSION="5.22"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.22"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by cissusnar** [comment]
今天的请求里面没有查到对应账号的linux设备登录记录, 猜测是没有成功连接服务器导致超时返回的错误

**Comment by little-snow-fox** [comment]
@cissusnar 经过检查，是因为系统代理导致 clipd 走了代理，关掉代理后能登录成功，请问可以提供一下 clipd 所请求的服务器域名吗？我想在 proxy 中加过滤规则。

**Comment by cissusnar** [comment]
iface.clipber.com

**Comment by little-snow-fox** [comment]
今天一早回来就出现如下报错，代理配置已经关掉
9196238eee3a:~/.config$ clipctl -U login
account: snow@sfxh.cc
passcode: 
failed, unknow error, upgrade client needed

samoyed@9196238eee3a:~/.config$ apt search clipd
Sorting... Done
Full Text Search... Done
clipd/unknown,now 1.0.2 amd64 [installed]
  corss platform clipboard app

samoyed@9196238eee3a:~/.config$ dpkg -l
ii  clipd                                         1.0.2                                          amd64
