### ISSUE TITLE
需求申请

### ISSUE THREAD

**Issue by senkawu** [cissusnar/kuaitie#36]
**平台**
e.g: Android | Windows

**需求描述**
希望可以有Linux客户端。

**解决了您的什么问题?**
可以跨平台在Linux中使用方便的快贴功能。

**附言**

**Comment by cissusnar** [comment]
Linux版本已经在开发中

**Comment by cissusnar** [comment]
Linux Beta版本已发布, 可以访问快贴主页来查看
https://clipber.com
