### ISSUE TITLE
报告BUG

### ISSUE THREAD

**Issue by Benature** [cissusnar/kuaitie#69]
**BUG描述**

**如何复现**
1. 下载后打开软件失败

**截屏**
![image](https://user-images.githubusercontent.com/35028647/88249306-b29e2e00-ccd6-11ea-8ccb-65424589bf65.png)

**桌面版:**
 - 系统版本: macOS 10.15.4 
 - 快贴版本: 2.1.7

**Comment by cissusnar** [comment]
感谢反馈, 之前的开发者账号过期了, 最近会更换一个重新打包一下

**Comment by Benature** [comment]
您好，请问什么时候可以更新安装包呢？或者有没有什么临时的替代方案？谢谢

**Comment by cissusnar** [comment]
您好, 明天下午的时候会更新一个新的开发者证书签名的包

**Comment by cissusnar** [comment]
请问你的机器上这个设置和图中的相同吗? 
<img width="664" alt="截屏2020-07-27 21 10 06" src="https://user-images.githubusercontent.com/2087003/88545573-c090dd80-d04d-11ea-80de-5c4389c61c61.png">

**Comment by Benature** [comment]
yep
![image](https://user-images.githubusercontent.com/35028647/88546058-6e9c8780-d04e-11ea-8cd2-560f795f6d6a.png)

**Comment by cissusnar** [comment]
收到, 最晚后天会更新一个新的开发者证书签名的包 : )

**Comment by Benature** [comment]
好的👌非常感谢🙇‍♂️

**Comment by cissusnar** [comment]
已更新签名包, 主站点击下载即可
另外mac上可以使用
`sudo spctl --master-disable`
命令来接触app安装限制  : )

**Comment by Benature** [comment]
已下载新的安装包，普通打开还是会和[之前](https://github.com/cissusnar/kuaitie/issues/69#issue-664176596)有警告，运行 `sudo` 命令行后强行打开了

**Comment by cissusnar** [comment]
抱歉, 刚刚发现, 这个问题和签名无关, 实际上是需要把安装包发送给苹果做公证才不会弹出这个提示. 
你可以使用
`sudo spctl --master-disable`
这个命令来允许mac运行第三方软件. 
新包正在提交给苹果做公证, 以后就不会出现这个问题了.
