### ISSUE TITLE
v2.1.12 复制并粘贴出来是 SYN(0x16)

### ISSUE THREAD

**Issue by mogu1121** [cissusnar/kuaitie#82]
Ctrl+v 正常

**Comment by cissusnar** [comment]
首先感谢反馈, 但反馈问题要提供足够详细有效的信息

**Comment by mogu1121** [comment]
Notepad++
![1](https://user-images.githubusercontent.com/21261903/94343363-3b747580-004a-11eb-8046-e44033a6fd00.gif)

**Comment by cissusnar** [comment]
感谢反馈, 下个版本会处理一下

**Comment by cissusnar** [comment]
2.1.13已修复
