### ISSUE TITLE
在 notepad++ 的编辑器里粘贴总是不成功

### ISSUE THREAD

**Issue by Y-JC** [cissusnar/kuaitie#83]
**BUG描述**
在 notepad++ 的编辑器里粘贴总是不成功（偶尔成功一两次），不仅如此，文本光标还从插入模式（光标为竖杠）变成覆盖模式（光标为横杠）；
在windows自带的文本编辑器里有时也会出现无法粘贴的情况；

**如何复现**
1.  win10
2.  notepadd++ 文本编辑器 v7.8.7 32bit，或 系统自带文本编辑器
3.  “复制并粘贴”

**桌面版:**
 - 系统版本: [Windows 10 pro 2004]
 - 快贴版本 [2.1.13]

**Comment by cissusnar** [comment]
2.1.15已修复
