### ISSUE TITLE
需求申请

### ISSUE THREAD

**Issue by xg805652411** [cissusnar/kuaitie#86]
**平台**
e.g: Android | Windows
android 10 华为荣耀p20 pro
**需求描述**
使用荣耀手机每次复制完，必须点一下快贴服务才同步到另一台安卓9的小米6x，而使用小米6x复制时，直接自动同步到了安卓10的荣耀手机上。软件需要的权限两台手机都给了。
求解决这个安卓10荣耀手机无法自动同步的问题

**解决了您的什么问题?**

**附言**

**Comment by cissusnar** [comment]
感谢反馈， Android 10 系统不再允许app后台获取剪贴板了
