### ISSUE TITLE
无法登录：ubuntu20.04输入clipd后回显1.0.0 (default, Aug 24 2020, 10:12:25)  [Clang 7.0.0 (git@github.com:apple/llvm-project.git c4513204aeb003122d2c69bd454 on Linux 5.4.0-42-generic

### ISSUE THREAD

**Issue by zjpzhao** [cissusnar/kuaitie#89]
**BUG描述**

**如何复现**
1. terminal输入clipd等命令

**截屏**

![image](https://user-images.githubusercontent.com/33554063/99091742-4049b480-260b-11eb-972b-bd65b9ea16cd.png)

**桌面版:**
 - 系统版本: [Ubuntu 20.04.1 LTS]
 - 快贴版本 [1.0.0 (default, Aug 24 2020, 10:12:25) ]

**附言**
...

**Comment by cissusnar** [comment]
感谢反馈, 可以先阅读一下Linux版本的使用方法 :)

https://blog.clipber.com/posts/linux-about/
