### ISSUE TITLE
需求申请

### ISSUE THREAD

**Issue by geligaoli** [cissusnar/kuaitie#9]
**平台**
linux archlinux ubuntu

**需求描述**
在linux上使用的版本。

**解决了您的什么问题?**
主要用linux工作。

**附言**
可否开放api等方式，由第三方增加功能？

**Comment by cissusnar** [comment]
linux上会以python SDK的方式发布

**Comment by cissusnar** [comment]
Linux Beta版本已发布, 可以访问快贴主页来查看
https://clipber.com
