### ISSUE TITLE
报告BUG：Mac版快贴安装完毕后，点击图标没反应。

### ISSUE THREAD

**Issue by vicvan0711** [cissusnar/kuaitie#92]
**BUG描述**
第一次安装Mac版快贴，安装后点击快贴图标没反应，怎么回事？系统版本是macos bigsur。
**如何复现**
1. 
2. 
3. 

**截屏**

**桌面版:**
 - 系统版本: [e.g. macOS 10.15 | Windows 10 build 1883]
 - 快贴版本 [e.g. 2.1.0]

**手机版:**
 - 设备: [e.g. iPhone6 | pixel 3a]
 - 系统版本: [e.g. iOS8.1 | Android 8]
 - 快贴版本 [e.g. 2.1.1]

**附言**
...

**Comment by cissusnar** [comment]
提问之前可以现查看FAQ  : )
