### ISSUE TITLE
安卓10为啥要打开软件才能跨平台同步？

### ISSUE THREAD

**Issue by kubage88** [cissusnar/kuaitie#93]
**平台**
e.g: Android | Windows

**需求描述**
我在三星s20手机上(安卓10)复制了一段文字，必须要打开快贴软件才能跨平台同步，why?

**解决了您的什么问题?**

**附言**

**Comment by cissusnar** [comment]
Android10+系统不再允许app后台读取剪贴板了

**Comment by kubage88** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    后面有没有可能出一个root版本，支持后台读取剪切板？😁
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                kubage88
                            
                    
                        
                            
                                    kubage88@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年02月6日 10:46，isaac zhang<notifications@github.com> 写道： 




Android10+系统不再允许app后台读取剪贴板了



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
